### ISSUE TITLE
请求502错误 程序意外终止问题

### ISSUE THREAD

**Issue by CrewS** [Rocket1184/qq-bot-rebown#1]
loopPoll 函数中 信息请求 有可能出现502的错误  导致程序意外终止
还有 handelMsgRecv(msg)  msg 有可能 返回 错误 {errmsg:'',retcode:''} 这样的数据 
不过这个是 之前的版本 你最新提交的 没有测试过····= -=

**Comment by rocka** [comment]
我也发现这个错误了，挂久了就会出现...
现在正在着手解决，测试好了就在发布一次 = =

**Comment by CrewS** [comment]
@Rocket1184  我上星期 是用了你上一个版本做了一个 群信息监听录入的程序。挂久了发现有些问题
 1 retcode的错误类型好像还挺多的 1002 
 2 好像登录有效期是24小时，会有一个登录失效的状态（这个状态码 还没记录到估计今晚失效的时候可以发现）

**Comment by rocka** [comment]
之前还可以挂两到三天的，现在不知道是不是又增加了限制
如果有登陆失效状态码的话还请务必告诉我

**Comment by rocka** [comment]
可以试试现在的 `0.1.4` 版本。我测试在线一天两小时没有掉线

大概每次登录可以维持两天。现在发生 502 错误时会要求重新登录了。
