### ISSUE TITLE
发生错误，在群消息时

### ISSUE THREAD

**Issue by ethan-phu** [Rocket1184/qq-bot-rebown#19]
![mark](http://7xvfyz.com1.z0.glb.clouddn.com/blog/171114/312Ge1GJ4G.png?imageslim)

**Comment by rocka** [comment]
should be fixed by

https://github.com/Rocket1184/qq-bot-rebown/commit/000fbcd75ec2752125ba64ff0e99260dfcb28d5a#diff-03e2dc3d9c8e65feb21a19eddce8339aR440
