### ISSUE TITLE
用cookie登录的话, 2天后就失效了

### ISSUE THREAD

**Issue by luopeizhen** [Rocket1184/qq-bot-rebown#21]
请问有试过登录2天后就要重新扫描登录吗, 我改成每隔5分钟登录一次, 这样cookie应该一直都是最新的, 可还是会出现要扫描登录

**Comment by rocka** [comment]
没办法，现在就是这样的，扫码两天之后就会被强制下线。
另外这个 Cookie 的 “新” 不是自己说了算，腾讯想让你下线，你就得重新扫码 ...
