### ISSUE TITLE
信息已发送但是仍然retcode=1202并且重发

### ISSUE THREAD

**Issue by Eroleice** [Rocket1184/qq-bot-rebown#23]
尤其是发送内容含有链接的时候。没有链接有时候也会。显示1202，重试N次，经常2-5连发刷屏……

有办法避免这种情况么？或者1202的情况干脆别重试了【或者给个disable的option？】

**Comment by rocka** [comment]
估计 WebQQ 又把 API 返回的内容改掉了 ...

暂时的办法，在 `node_modules/qq-bot-rebown/src/qq/index.js` 里面，去掉 590-597 行的这个 `else` 分支：

https://github.com/Rocket1184/qq-bot-rebown/blob/bd0113f861e78bb7e8df588f4958d58a7607a849/src/qq/index.js#L590-L597

稍后我再看一下怎么有效的判断消息是否发送成功，或者干脆加个不判断消息是否发送成功的选项 ...

**Comment by rocka** [comment]
closed via 7a3b08c
