### ISSUE TITLE
一起搞个机器人来卖？

### ISSUE THREAD

**Issue by myafer** [Rocket1184/qq-bot-rebown#24]
一起搞个机器人来卖？

**Comment by rocka** [comment]
这个项目稳定性很差的。如果你真想卖点什么，建议左转 https://cqp.cc/

**Comment by myafer** [comment]
哈哈，这东西可以慢慢优化啊。我想有空的时候把他做成electron的，最近在区块链群当管理，要用到些功能，用的Mac，酷Q也没法用。所以有这个想法
