### ISSUE TITLE
获取群信息失败

### ISSUE THREAD

**Issue by tongjinle** [Rocket1184/qq-bot-rebown#28]
<img width="1277" alt="screen shot 2018-04-03 at 6 27 42 pm" src="https://user-images.githubusercontent.com/1735345/38244304-cbd42750-376c-11e8-95b4-22bd3e83022f.png">

**Comment by rocka** [comment]
最近也有这个问题，有时就会失败，重新登录以后就正常了。

但奇怪的是有的群又能正常获取到信息，不知道怎么回事 ...

**Comment by tongjinle** [comment]
我提交了[pr](https://github.com/Rocket1184/qq-bot-rebown/pull/29)
