### ISSUE TITLE
无法获取消息，一直显示重新登录

### ISSUE THREAD

**Issue by catchstar** [Rocket1184/qq-bot-rebown#30]
![image](https://user-images.githubusercontent.com/8263734/39566192-53c5e9ea-4eed-11e8-893b-d5123186a367.png)

**Comment by rocka** [comment]
可能是 WebQQ 的登录验证流程又改了吧

**Comment by rocka** [comment]
reference: https://github.com/ScienJus/qqbot/pull/5
