### ISSUE TITLE
大神,这个能不能集成到electron-vue里面？给个集成的demo好吗

### ISSUE THREAD

**Issue by purestart** [Rocket1184/qq-bot-rebown#31]
我把它放在electron主线程里面都不执行
import { app, BrowserWindow } from 'electron'
const {ipcMain} = require('electron');
import {QQ} from 'qq-bot-rebown';
const qq = new QQ();
qq.on('msg', (msg) => {
    console.log(JSON.stringify(msg));
});
qq.on('buddy', (msg) => {
    qq.sendBuddyMsg(msg.id, `Hello, ${msg.name}`);
});
qq.run();

**Comment by rocka** [comment]
刚试了一下，用 `electron` 运行的话的确没法收到消息，不知道哪里出毛病了 ...

**Comment by rocka** [comment]
刚发布的 `2.1.8` 已经解决了这个问题，可以在 electron 正常使用。

**Comment by purestart** [comment]
谢谢你，现在可以使用了，给你star和fork了，赞一个
不过使用前我注释些代码，牺牲了密码登录功能
headless.js下删除了puppeteer的导入，electron好像不支持node的一些模块
const fs = require('fs');
const os = require('os');
const { join, sep } = require('path');
const Log = require('log');
//const Puppeteer = require('puppeteer');
const Puppeteer = {};
。。。
在utils/index.js下做了些修改，electron好像也不支持promisify这个方法
const fs = require('fs');
const util = require('util');
require('util.promisify').shim();
const cp = require('child_process');
。。。
顺便问一下，你在electron下这两个功能都能用吗？你是如何设置的？

**Comment by rocka** [comment]
electron 的版本是多少？我测试在 `1.8.4` 都是能支持的，建议升级一下。
