### ISSUE TITLE
这两天获取好友和获取群一直失败

### ISSUE THREAD

**Issue by purestart** [Rocket1184/qq-bot-rebown#32]
[Fri May 25 2018 17:47:14 GMT+0800 (中国标准时间)] WARNING 尝试获取好友列表时失败： { retcode: 100003,
    result:
     { friends:
        [ [Object],

[Fri May 25 2018 17:52:21 GMT+0800 (中国标准时间)] WARNING 尝试获取群信息时失败： { retcode: 100003,
    result:
     { ginfo:
        { face: 0,
          memo: '',
不知道什么问题，前几天还是可以的，几天没用，今天打开就这样了，群信息可以收到，但是群里面的好友名字是uin

**Comment by rocka** [comment]
是在什么环境下运行的，自己的机器还是 VPS ？我这边不能复现，好友列表和群消息都是正常的。
