### ISSUE TITLE
是否可以发送图片信息

### ISSUE THREAD

**Issue by tongjinle** [Rocket1184/qq-bot-rebown#8]
RT
我尝试了用官方web版的qq
我在webqq上登陆了我的qq A
我在客户端上登陆了我的qq B
我使用B对A发送了图片,但是A上没有能接收到(严格来说,可能是接受到了信息,但是没有显示出来)

是webqq就是不可以发送接受图片,还是我漏看了什么

**Comment by rocka** [comment]
Web QQ 现在确实无法发送以及接收图片消息，而且可用的功能还在渐渐减少
