### ISSUE TITLE
自己在群里发言 msg.name = undefined.

### ISSUE THREAD

**Issue by Jonathan-Fan** [Rocket1184/qq-bot-rebown#9]
不知道是feature 还是 bug 😂 , 用我自己的号login, 然后在手机上也用自己的号在群里发消息, msg.name 是 undefined
```
[Wed Aug 16 2017 16:44:17 GMT+1000 (AEST)] INFO [群消息] xxxxxxxxx : undefined | 你们打才有用
```

**Comment by rocka** [comment]
其实之前是不能收到自己发出的消息的，不知道什么时候加上的。。。

试着修一下，当查不到名字的时候就认为是自己好了 😅

**Comment by rocka** [comment]
closed via 429afdb
